
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_RESERVATIONS_PENDING = 'REQUEST_RESERVATIONS_PENDING'
export const REQUEST_RESERVATIONS_SUCCESS = 'REQUEST_RESERVATIONS_SUCCESS'
export const REQUEST_RESERVATIONS_FAILED = 'REQUEST_RESERVATIONS_FAILED'

export const REQUEST_LOANERS_PENDING = 'REQUEST_LOANERS_PENDING'
export const REQUEST_LOANERS_SUCCESS = 'REQUEST_LOANERS_SUCCESS'
export const REQUEST_LOANERS_FAILED = 'REQUEST_LOANERS_FAILED'

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING'
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS'
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED'